# /ai_rag_story_app/alembic/script.py.mako
"""add_character_generator_fields

Revision ID: 012f4453cea5
Revises: 57ba6a518ddf
Create Date: 2025-07-01 18:06:33.750093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '012f4453cea5'
down_revision: Union[str, None] = '57ba6a518ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('core_motivation', sa.String(length=255), nullable=True))
    op.add_column('characters', sa.Column('physical_attributes', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('key_relationships', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('genre', sa.String(length=100), nullable=True))
    op.add_column('characters', sa.Column('genre_specific_answers', sa.JSON(), nullable=True))
    op.add_column('characters', sa.Column('generated_narrative', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('is_ai_generated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_ai_generated')
    op.drop_column('characters', 'generated_narrative')
    op.drop_column('characters', 'genre_specific_answers')
    op.drop_column('characters', 'genre')
    op.drop_column('characters', 'key_relationships')
    op.drop_column('characters', 'physical_attributes')
    op.drop_column('characters', 'core_motivation')
    # ### end Alembic commands ###