# /ai_rag_story_app/alembic/script.py.mako
"""Add brainstorm session tables

Revision ID: 0bdb872a5428
Revises: 6c2d20a022a8
Create Date: 2025-07-12 13:18:30.582592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdb872a5428'
down_revision: Union[str, None] = '6c2d20a022a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###