# /ai_rag_story_app/alembic/script.py.mako
"""Add image support to World model

Revision ID: 242cbfaa7a13
Revises: 74ed04d00b8a
Create Date: 2025-06-16 11:24:34.308565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242cbfaa7a13'
down_revision: Union[str, None] = '74ed04d00b8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('image_prompt_definition', sa.Text(), nullable=True))
    op.add_column('worlds', sa.Column('image_blob_path', sa.String(length=1024), nullable=True))
    op.add_column('worlds', sa.Column('current_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'worlds', 'generated_images', ['current_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'worlds', type_='foreignkey')
    op.drop_column('worlds', 'current_image_id')
    op.drop_column('worlds', 'image_blob_path')
    op.drop_column('worlds', 'image_prompt_definition')
    # ### end Alembic commands ###