# /ai_rag_story_app/alembic/script.py.mako
"""Add story chat sessions and messages

Revision ID: 367d8bea312a
Revises: 50074159797a
Create Date: 2025-07-08 21:00:50.863790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '367d8bea312a'
down_revision: Union[str, None] = '50074159797a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('story_type', sa.String(length=20), server_default='advanced', nullable=False))
    op.create_index(op.f('ix_stories_story_type'), 'stories', ['story_type'], unique=False)
    op.add_column('worlds', sa.Column('is_shadow', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_worlds_is_shadow'), 'worlds', ['is_shadow'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worlds_is_shadow'), table_name='worlds')
    op.drop_column('worlds', 'is_shadow')
    op.drop_index(op.f('ix_stories_story_type'), table_name='stories')
    op.drop_column('stories', 'story_type')
    # ### end Alembic commands ###