# /ai_rag_story_app/alembic/script.py.mako
"""Add brainstorm session models for Story Brainstorm feature

Revision ID: 4048b1f55b83
Revises: 15e5388ec73d
Create Date: 2025-07-12 14:04:40.460964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4048b1f55b83'
down_revision: Union[str, None] = '15e5388ec73d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###