# /ai_rag_story_app/alembic/script.py.mako
"""Add ai_summary fields to stories, acts, and scenes

Revision ID: 474bda25467b
Revises: d8fb24cfe3bc
Create Date: 2025-06-25 09:12:10.596287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '474bda25467b'
down_revision: Union[str, None] = 'd8fb24cfe3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###