# /ai_rag_story_app/alembic/script.py.mako
"""add_oauth_fields_to_users


Revision ID: 4ce3ce03db42
Revises: f6f820dc421b
Create Date: 2025-07-08 09:39:48.969612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ce3ce03db42'
down_revision: Union[str, None] = 'f6f820dc421b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_share_daily_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('total_shares', sa.Integer(), nullable=False),
    sa.Column('coins_earned', sa.Integer(), nullable=False),
    sa.Column('max_coins_reached', sa.Boolean(), nullable=False),
    sa.Column('facebook_shares', sa.Integer(), nullable=False),
    sa.Column('twitter_shares', sa.Integer(), nullable=False),
    sa.Column('linkedin_shares', sa.Integer(), nullable=False),
    sa.Column('reddit_shares', sa.Integer(), nullable=False),
    sa.Column('whatsapp_shares', sa.Integer(), nullable=False),
    sa.Column('email_shares', sa.Integer(), nullable=False),
    sa.Column('copy_link_shares', sa.Integer(), nullable=False),
    sa.Column('pinterest_shares', sa.Integer(), nullable=False),
    sa.Column('telegram_shares', sa.Integer(), nullable=False),
    sa.Column('image_preview_shares', sa.Integer(), nullable=False),
    sa.Column('published_story_shares', sa.Integer(), nullable=False),
    sa.Column('ai_public_chat_shares', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_share_daily_summaries_date'), 'social_share_daily_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_social_share_daily_summaries_id'), 'social_share_daily_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_social_share_daily_summaries_user_id'), 'social_share_daily_summaries', ['user_id'], unique=False)
    op.create_table('social_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_id', sa.String(length=255), nullable=False),
    sa.Column('content_title', sa.String(length=500), nullable=True),
    sa.Column('content_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('shared_text', sa.Text(), nullable=True),
    sa.Column('shared_hashtags', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.Text(), nullable=True),
    sa.Column('coin_awarded', sa.Boolean(), nullable=False),
    sa.Column('coin_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_shares_coin_awarded'), 'social_shares', ['coin_awarded'], unique=False)
    op.create_index(op.f('ix_social_shares_content_id'), 'social_shares', ['content_id'], unique=False)
    op.create_index(op.f('ix_social_shares_content_type'), 'social_shares', ['content_type'], unique=False)
    op.create_index(op.f('ix_social_shares_created_at'), 'social_shares', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_shares_id'), 'social_shares', ['id'], unique=False)
    op.create_index(op.f('ix_social_shares_platform'), 'social_shares', ['platform'], unique=False)
    op.create_index(op.f('ix_social_shares_user_id'), 'social_shares', ['user_id'], unique=False)
    # Add auth_provider column with a default value first
    op.add_column('users', sa.Column('auth_provider', sa.String(length=50), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE users SET auth_provider = 'local' WHERE auth_provider IS NULL")
    # Now make it NOT NULL
    op.alter_column('users', 'auth_provider', nullable=False)
    
    # Add other OAuth columns
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('provider_data', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['provider_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'provider_data')
    op.drop_column('users', 'provider_id')
    op.drop_column('users', 'auth_provider')
    op.drop_index(op.f('ix_social_shares_user_id'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_platform'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_id'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_created_at'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_content_type'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_content_id'), table_name='social_shares')
    op.drop_index(op.f('ix_social_shares_coin_awarded'), table_name='social_shares')
    op.drop_table('social_shares')
    op.drop_index(op.f('ix_social_share_daily_summaries_user_id'), table_name='social_share_daily_summaries')
    op.drop_index(op.f('ix_social_share_daily_summaries_id'), table_name='social_share_daily_summaries')
    op.drop_index(op.f('ix_social_share_daily_summaries_date'), table_name='social_share_daily_summaries')
    op.drop_table('social_share_daily_summaries')
    # ### end Alembic commands ###