# /ai_rag_story_app/alembic/script.py.mako
"""add_current_image_id_to_acts

Revision ID: 57ba6a518ddf
Revises: 71aab816dd09
Create Date: 2025-06-30 12:39:02.641414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ba6a518ddf'
down_revision: Union[str, None] = '71aab816dd09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('current_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'acts', 'generated_images', ['current_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'acts', type_='foreignkey')
    op.drop_column('acts', 'current_image_id')
    # ### end Alembic commands ###