# /ai_rag_story_app/alembic/script.py.mako
"""Add QUICK_AI prompt type and sample prompts

Revision ID: 645076dc14c2
Revises: 02a3b2386ced
Create Date: 2025-07-15 11:06:52.516747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '645076dc14c2'
down_revision: Union[str, None] = '02a3b2386ced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###