# /ai_rag_story_app/alembic/script.py.mako
"""Add story metadata fields and new prompt types

Revision ID: 688359a08e08
Revises: fix_add_ai_summary
Create Date: 2025-06-26 09:45:15.741382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688359a08e08'
down_revision: Union[str, None] = 'fix_add_ai_summary'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('story_genre', sa.String(length=100), nullable=True))
    op.add_column('stories', sa.Column('story_tone', sa.String(length=100), nullable=True))
    op.add_column('stories', sa.Column('primary_conflict_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'primary_conflict_type')
    op.drop_column('stories', 'story_tone')
    op.drop_column('stories', 'story_genre')
    # ### end Alembic commands ###