# /ai_rag_story_app/alembic/script.py.mako
"""add species and core_motivations fields to characters

Revision ID: 6af43ceaab21
Revises: 012f4453cea5
Create Date: 2025-07-01 20:46:35.808092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af43ceaab21'
down_revision: Union[str, None] = '012f4453cea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('gender', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('species', sa.String(length=100), nullable=True))
    op.add_column('characters', sa.Column('core_motivations', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'core_motivations')
    op.drop_column('characters', 'species')
    op.drop_column('characters', 'gender')
    # ### end Alembic commands ###