# /ai_rag_story_app/alembic/script.py.mako
"""Add user interview            │
│   responses table

Revision ID: 6c2d20a022a8
Revises: 59a3f4301bba
Create Date: 2025-07-11 10:58:09.659675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2d20a022a8'
down_revision: Union[str, None] = '59a3f4301bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interview_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.String(length=100), nullable=False),
    sa.Column('json_response', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_interview_responses_id'), 'user_interview_responses', ['id'], unique=False)
    op.create_index(op.f('ix_user_interview_responses_interview_id'), 'user_interview_responses', ['interview_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_interview_responses_interview_id'), table_name='user_interview_responses')
    op.drop_index(op.f('ix_user_interview_responses_id'), table_name='user_interview_responses')
    op.drop_table('user_interview_responses')
    # ### end Alembic commands ###