# /ai_rag_story_app/alembic/script.py.mako
"""Add referral tracking system tables

Revision ID: 7cb2cea8948c
Revises: final_merge_all_heads
Create Date: 2025-07-17 22:21:58.038339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cb2cea8948c'
down_revision: Union[str, None] = 'final_merge_all_heads'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blog_categories_slug_key'), 'blog_categories', type_='unique')
    op.drop_index(op.f('ix_blog_categories_slug'), table_name='blog_categories')
    op.create_index(op.f('ix_blog_categories_slug'), 'blog_categories', ['slug'], unique=True)
    op.alter_column('blog_post_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('blog_posts_slug_key'), 'blog_posts', type_='unique')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.drop_constraint(op.f('blog_tags_name_key'), 'blog_tags', type_='unique')
    op.drop_constraint(op.f('blog_tags_slug_key'), 'blog_tags', type_='unique')
    op.drop_index(op.f('ix_blog_tags_name'), table_name='blog_tags')
    op.create_index(op.f('ix_blog_tags_name'), 'blog_tags', ['name'], unique=True)
    op.drop_index(op.f('ix_blog_tags_slug'), table_name='blog_tags')
    op.create_index(op.f('ix_blog_tags_slug'), 'blog_tags', ['slug'], unique=True)
    # Add referral columns to users table
    op.add_column('users', sa.Column('referred_by_user_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('referral_count', sa.Integer(), nullable=True, server_default='0'))
    
    # Update existing users to have referral_count = 0
    op.execute("UPDATE users SET referral_count = 0 WHERE referral_count IS NULL")
    
    # Now make referral_count NOT NULL
    op.alter_column('users', 'referral_count', nullable=False)
    
    # Add foreign key constraint
    op.create_foreign_key(None, 'users', 'users', ['referred_by_user_id'], ['id'], ondelete='SET NULL')
    
    # Create referrals table
    op.create_table('referrals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('referrer_user_id', sa.Integer(), nullable=False),
        sa.Column('referred_user_id', sa.Integer(), nullable=True),
        sa.Column('anonymous_session_id', sa.String(255), nullable=True),
        sa.Column('source_platform', sa.String(50), nullable=True),
        sa.Column('source_content_type', sa.String(50), nullable=True),
        sa.Column('source_content_id', sa.String(100), nullable=True),
        sa.Column('referral_url', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(45), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('is_converted', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('has_created_story', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('has_published_story', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ondelete='CASCADE')
    )
    op.create_index('ix_referrals_referrer_user_id', 'referrals', ['referrer_user_id'])
    op.create_index('ix_referrals_referred_user_id', 'referrals', ['referred_user_id'])
    op.create_index('ix_referrals_anonymous_session_id', 'referrals', ['anonymous_session_id'])
    
    # Create referral_rewards table
    op.create_table('referral_rewards',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('referral_id', sa.Integer(), nullable=False),
        sa.Column('reward_type', sa.String(50), nullable=False),
        sa.Column('coin_amount', sa.Integer(), nullable=False),
        sa.Column('awarded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE')
    )
    op.create_index('ix_referral_rewards_user_id', 'referral_rewards', ['user_id'])
    op.create_index('ix_referral_rewards_referral_id', 'referral_rewards', ['referral_id'])
    
    # Create referral_limits table
    op.create_table('referral_limits',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('total_coins_earned', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('visit_rewards_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('registration_rewards_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('story_rewards_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('publish_rewards_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.UniqueConstraint('user_id', 'date', name='uq_referral_limits_user_date')
    )
    op.create_index('ix_referral_limits_user_id', 'referral_limits', ['user_id'])
    op.create_index('ix_referral_limits_date', 'referral_limits', ['date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop referral tables
    op.drop_table('referral_limits')
    op.drop_table('referral_rewards')
    op.drop_table('referrals')
    
    # Drop referral columns from users table
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referral_count')
    op.drop_column('users', 'referred_by_user_id')
    op.drop_index(op.f('ix_blog_tags_slug'), table_name='blog_tags')
    op.create_index(op.f('ix_blog_tags_slug'), 'blog_tags', ['slug'], unique=False)
    op.drop_index(op.f('ix_blog_tags_name'), table_name='blog_tags')
    op.create_index(op.f('ix_blog_tags_name'), 'blog_tags', ['name'], unique=False)
    op.create_unique_constraint(op.f('blog_tags_slug_key'), 'blog_tags', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('blog_tags_name_key'), 'blog_tags', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=False)
    op.create_unique_constraint(op.f('blog_posts_slug_key'), 'blog_posts', ['slug'], postgresql_nulls_not_distinct=False)
    op.alter_column('blog_post_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_blog_categories_slug'), table_name='blog_categories')
    op.create_index(op.f('ix_blog_categories_slug'), 'blog_categories', ['slug'], unique=False)
    op.create_unique_constraint(op.f('blog_categories_slug_key'), 'blog_categories', ['slug'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###