# /ai_rag_story_app/alembic/script.py.mako
"""Add AI Summary

Revision ID: 80ca7de98931
Revises: 50ca759df885
Create Date: 2025-06-24 17:29:05.885919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80ca7de98931'
down_revision: Union[str, None] = '50ca759df885'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('scenes', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'ai_summary')
    op.drop_column('scenes', 'ai_summary')
    op.drop_column('acts', 'ai_summary')
    # ### end Alembic commands ###