# /ai_rag_story_app/alembic/script.py.mako
"""add_chat_samples_table

Revision ID: 96bba0a9b82e
Revises: add_anonymous_sessions
Create Date: 2025-06-21 13:12:04.604153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96bba0a9b82e'
down_revision: Union[str, None] = 'add_anonymous_sessions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_samples_id'), 'chat_samples', ['id'], unique=False)
    op.drop_index(op.f('ix_anonymous_sessions_browser_fingerprint'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_sessions_created_at'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_sessions_ip_address'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_sessions_session_token'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_sessions_user_id'), table_name='anonymous_user_sessions')
    op.create_index(op.f('ix_anonymous_user_sessions_browser_fingerprint'), 'anonymous_user_sessions', ['browser_fingerprint'], unique=False)
    op.create_index(op.f('ix_anonymous_user_sessions_created_at'), 'anonymous_user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_anonymous_user_sessions_id'), 'anonymous_user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_anonymous_user_sessions_ip_address'), 'anonymous_user_sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_anonymous_user_sessions_session_token'), 'anonymous_user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_anonymous_user_sessions_user_id'), 'anonymous_user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anonymous_user_sessions_user_id'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_user_sessions_session_token'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_user_sessions_ip_address'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_user_sessions_id'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_user_sessions_created_at'), table_name='anonymous_user_sessions')
    op.drop_index(op.f('ix_anonymous_user_sessions_browser_fingerprint'), table_name='anonymous_user_sessions')
    op.create_index(op.f('ix_anonymous_sessions_user_id'), 'anonymous_user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_anonymous_sessions_session_token'), 'anonymous_user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_anonymous_sessions_ip_address'), 'anonymous_user_sessions', ['ip_address'], unique=False)
    op.create_index(op.f('ix_anonymous_sessions_created_at'), 'anonymous_user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_anonymous_sessions_browser_fingerprint'), 'anonymous_user_sessions', ['browser_fingerprint'], unique=False)
    op.drop_index(op.f('ix_chat_samples_id'), table_name='chat_samples')
    op.drop_table('chat_samples')
    # ### end Alembic commands ###