# /ai_rag_story_app/alembic/script.py.mako
"""Add bonus reward tracking columns to users table

Revision ID: 9ab456de105b
Revises: eb21c696ad50
Create Date: 2025-07-13 16:58:41.560467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ab456de105b'
down_revision: Union[str, None] = 'eb21c696ad50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###