# /ai_rag_story_app/alembic/script.py.mako
"""add_world_chat_tables

Revision ID: aa94832e4171
Revises: 9b59a68ffd34
Create Date: 2025-06-19 09:47:06.674590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa94832e4171'
down_revision: Union[str, None] = '9b59a68ffd34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###