# /ai_rag_story_app/alembic/script.py.mako
"""Add world builder fields to worlds table

Revision ID: b15c28e525e0
Revises: 7dfb4c0d7070
Create Date: 2025-07-02 14:55:21.864575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b15c28e525e0'
down_revision: Union[str, None] = '7dfb4c0d7070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('worlds', sa.Column('short_description', sa.Text(), nullable=True))
    op.add_column('worlds', sa.Column('world_builder_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worlds', 'world_builder_data')
    op.drop_column('worlds', 'short_description')
    # ### end Alembic commands ###