# /ai_rag_story_app/alembic/script.py.mako
"""Add character generator
      fields: next_quest_scenario, first_meeting_message,
      age_category, profession

Revision ID: d0a85be06b14
Revises: 6af43ceaab21
Create Date: 2025-07-02 09:53:09.404694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a85be06b14'
down_revision: Union[str, None] = '6af43ceaab21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('next_quest_scenario', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('first_meeting_message', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('age_category', sa.String(length=50), nullable=True))
    op.add_column('characters', sa.Column('profession', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'profession')
    op.drop_column('characters', 'age_category')
    op.drop_column('characters', 'first_meeting_message')
    op.drop_column('characters', 'next_quest_scenario')
    # ### end Alembic commands ###