# /ai_rag_story_app/alembic/script.py.mako
"""Add bonus tracking columns to users table

Revision ID: d6715a14a088
Revises: 9ab456de105b
Create Date: 2025-07-13 17:02:48.941505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6715a14a088'
down_revision: Union[str, None] = '9ab456de105b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add bonus columns with default values for existing rows
    op.add_column('users', sa.Column('bonus1', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus2', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus3', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus4', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus5', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus6', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus7', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus8', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus9', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('bonus10', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bonus10')
    op.drop_column('users', 'bonus9')
    op.drop_column('users', 'bonus8')
    op.drop_column('users', 'bonus7')
    op.drop_column('users', 'bonus6')
    op.drop_column('users', 'bonus5')
    op.drop_column('users', 'bonus4')
    op.drop_column('users', 'bonus3')
    op.drop_column('users', 'bonus2')
    op.drop_column('users', 'bonus1')
    # ### end Alembic commands ###