# /ai_rag_story_app/alembic/script.py.mako
"""Add password reset fields to users table

Revision ID: d7d81518cde0
Revises: 325d50bd67d4
Create Date: 2025-07-18 13:32:00.473844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7d81518cde0'
down_revision: Union[str, None] = '325d50bd67d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_rewards_referral_id'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_user_id'), table_name='referral_rewards')
    op.drop_table('referral_rewards')
    op.drop_index(op.f('ix_referral_limits_date'), table_name='referral_limits')
    op.drop_index(op.f('ix_referral_limits_user_id'), table_name='referral_limits')
    op.drop_table('referral_limits')
    op.drop_index(op.f('ix_referrals_anonymous_session_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.add_column('users', sa.Column('reset_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.create_table('referrals',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('referrals_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referred_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anonymous_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('source_platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_content_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('referral_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_converted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('has_created_story', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('has_published_story', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('referral_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('first_story_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('first_publish_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name='referrals_referred_user_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name='referrals_referrer_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_anonymous_session_id'), 'referrals', ['anonymous_session_id'], unique=False)
    op.create_table('referral_limits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_coins_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('visit_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('registration_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('story_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('publish_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('referral_limits_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_limits_pkey')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('uq_referral_limits_user_date'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_referral_limits_user_id'), 'referral_limits', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_limits_date'), 'referral_limits', ['date'], unique=False)
    op.create_table('referral_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referral_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('coin_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('referral_rewards_referral_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('referral_rewards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_rewards_pkey'))
    )
    op.create_index(op.f('ix_referral_rewards_user_id'), 'referral_rewards', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_referral_id'), 'referral_rewards', ['referral_id'], unique=False)
    # ### end Alembic commands ###