# /ai_rag_story_app/alembic/script.py.mako
"""add_interview_data_to_user

Revision ID: eb21c696ad50
Revises: 0b51f08c832c
Create Date: 2025-07-13 10:33:19.110130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb21c696ad50'
down_revision: Union[str, None] = '0b51f08c832c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interview_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'interview_data')
    # ### end Alembic commands ###