"""Pydantic schemas for character."""

# /story_app/app/schemas/character.py

from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from datetime import datetime

class GenreQuestionAnswer(BaseModel):
    """Schema for genre-specific question and answer"""
    question: str
    answer: str

class CharacterBase(BaseModel):
    """Base Pydantic model for a Character."""
    name: str = Field(..., min_length=1, max_length=255, description="The name of the character.")
    gender: Optional[str] = Field(None, max_length=50, description="The gender of the character.")
    species: Optional[str] = Field(None, max_length=100, description="The species of the character.")
    description: Optional[str] = Field(None, description="A general description of the character.")
    personality_traits: Optional[str] = Field(None, description="Key personality traits of the character (e.g., comma-separated or free text).")
    backstory: Optional[str] = Field(None, description="A summary of the character's backstory.")
    image_prompt_definition: Optional[str] = Field(None, description="Text prompt for generating an image of this character.")
    image_blob_path: Optional[str] = Field(None, max_length=1024, description="Path to the character's image in storage.")
    
    current_location_id: Optional[int] = Field(None, description="ID of the location where this character is currently placed")
    placement_note: Optional[str] = Field(None, description="Description of how/where the character is placed at the location")
    
    # AI import fields
    importance_rating: Optional[int] = Field(None, ge=1, le=5, description="Significance to the story (1=minor, 5=main protagonist/antagonist)")
    relationships: Optional[str] = Field(None, description="Key relationships to other characters, locations, or lore items")
    
    # Character generator fields
    core_motivation: Optional[str] = Field(None, max_length=255, description="Character's primary motivation (legacy)")
    core_motivations: Optional[List[str]] = Field(None, max_items=3, description="Character's primary motivations (1-3)")
    physical_attributes: Optional[Dict[str, Any]] = Field(None, description="Physical characteristics (hair color, eye color, etc.)")
    key_relationships: Optional[Dict[str, Any]] = Field(None, description="Key relationships with other characters")
    genre: Optional[str] = Field(None, max_length=100, description="Genre context for character generation")
    genre_specific_answers: Optional[Dict[str, Any]] = Field(None, description="Answers to genre-specific questions")
    generated_narrative: Optional[str] = Field(None, description="AI-generated character backstory")
    is_ai_generated: Optional[bool] = Field(False, description="Whether this character was generated by AI")
    
    # New character generator fields
    next_quest_scenario: Optional[str] = Field(None, description="A possible scenario of what the character would plan to do in their next quest")
    first_meeting_message: Optional[str] = Field(None, description="What the character would say when meeting someone for the first time")
    age_category: Optional[str] = Field(None, max_length=50, description="Age category of the character")
    profession: Optional[str] = Field(None, max_length=100, description="Character's profession or occupation")
    short_backstory: Optional[str] = Field(None, description="A short (50 words max) version of the character's backstory")
    visual_prompt: Optional[str] = Field(None, description="AI-generated prompt for visual character representation")
    narrative_filter_results: Optional[Dict[str, Any]] = Field(None, description="AI content filter results from narrative generation")

class CharacterCreate(CharacterBase):
    """Pydantic model for creating a new Character. world_id will be path/contextual."""
    pass

class CharacterUpdate(BaseModel):
    """Pydantic model for updating an existing Character. All fields are optional."""
    name: Optional[str] = Field(None, min_length=1, max_length=255)
    description: Optional[str] = Field(None)
    personality_traits: Optional[str] = Field(None)
    backstory: Optional[str] = Field(None)
    image_prompt_definition: Optional[str] = Field(None)
    image_blob_path: Optional[str] = Field(None, max_length=1024)
    importance_rating: Optional[int] = Field(None, ge=1, le=5)
    relationships: Optional[str] = Field(None)
    
    current_location_id: Optional[int] = Field(None)
    placement_note: Optional[str] = Field(None)
    
    # Character generator fields
    core_motivation: Optional[str] = Field(None, max_length=255)
    physical_attributes: Optional[Dict[str, Any]] = Field(None)
    key_relationships: Optional[Dict[str, Any]] = Field(None)
    genre: Optional[str] = Field(None, max_length=100)
    genre_specific_answers: Optional[Dict[str, Any]] = Field(None)
    generated_narrative: Optional[str] = Field(None)
    is_ai_generated: Optional[bool] = Field(None)
    
    # New character generator fields
    next_quest_scenario: Optional[str] = Field(None)
    first_meeting_message: Optional[str] = Field(None)
    age_category: Optional[str] = Field(None, max_length=50)
    profession: Optional[str] = Field(None, max_length=100)
    short_backstory: Optional[str] = Field(None)
    visual_prompt: Optional[str] = Field(None)
    narrative_filter_results: Optional[Dict[str, Any]] = Field(None)

class CharacterRead(CharacterBase):
    """Pydantic model for representing a Character in API responses."""
    id: int
    world_id: int
    
    # --- FIX: Add the image_url field ---
    image_url: Optional[str] = None

    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

class StoryCharacterLinkCreate(BaseModel):
    """Schema for linking a character to a story and defining their role."""
    character_id: int
    role_in_story: Optional[str] = Field(None, max_length=255, description="The character's role in this specific story (e.g., Protagonist).")

class StoryCharacterLinkRead(BaseModel):
    """Schema for reading the details of a story-character link, including the character info."""
    story_id: int
    character_id: int
    role_in_story: Optional[str] = None
    character: CharacterRead

    class Config:
        from_attributes = True

class CharacterInStoryRead(BaseModel):
    """Schema for listing characters associated with a story, showing their role."""
    id: int
    name: str
    description: Optional[str] = None
    role_in_story: Optional[str] = None
    
    # --- FIX: Add the image_url field here as well ---
    image_url: Optional[str] = None

    class Config:
        from_attributes = True

# Character Generation Schemas
class PhysicalAttributes(BaseModel):
    """Schema for character physical attributes"""
    hair_color: Optional[str] = None
    eye_color: Optional[str] = None
    build: Optional[str] = None
    height: Optional[str] = None

class KeyRelationship(BaseModel):
    """Schema for a single key relationship"""
    person: str
    dynamic: str

class CharacterGeneratorInput(BaseModel):
    """Schema for character generator wizard input"""
    name: Optional[str] = Field(None, description="Character name (optional for random generation)")
    gender: Optional[str] = Field(None, description="Character gender")
    species: Optional[str] = Field(None, description="Character species")
    personality_traits: Optional[List[str]] = Field(None, description="Selected personality traits")
    core_motivations: Optional[List[str]] = Field(None, max_items=3, description="Primary motivations (1-3)")
    physical_attributes: Optional[PhysicalAttributes] = Field(None, description="Physical characteristics")
    key_relationships: Optional[List[KeyRelationship]] = Field(None, description="Key relationships")
    genre: Optional[str] = Field(None, description="Selected genre")
    genre_specific_answers: Optional[List[GenreQuestionAnswer]] = Field(None, description="Genre-specific Q&A")
    age_category: Optional[str] = Field(None, description="Character's age category")
    profession: Optional[str] = Field(None, description="Character's profession or occupation")
    is_random_generation: bool = Field(False, description="Whether this is random generation")

class CharacterGeneratorResult(BaseModel):
    """Schema for character generator result with success/error handling"""
    success: bool = Field(..., description="Whether the generation was successful")
    character: Optional[CharacterRead] = Field(None, description="Generated character if successful")
    redirect_url: Optional[str] = Field(None, description="URL to redirect to after creation")
    error: Optional[str] = Field(None, description="Error message if generation failed")
    generation_metadata: Optional[Dict[str, Any]] = Field(None, description="Metadata about the generation process")

