# /ai_rag_story_app/alembic/script.py.mako
"""Add short_backstory and         │
│   visual_prompt fields to character model

Revision ID: 0910c7356ef6
Revises: d0a85be06b14
Create Date: 2025-07-02 10:22:01.296382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0910c7356ef6'
down_revision: Union[str, None] = 'd0a85be06b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('short_backstory', sa.Text(), nullable=True))
    op.add_column('characters', sa.Column('visual_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'visual_prompt')
    op.drop_column('characters', 'short_backstory')
    # ### end Alembic commands ###