# /ai_rag_story_app/alembic/script.py.mako
"""Add brainstorm session models

Revision ID: 0b51f08c832c
Revises: 4048b1f55b83
Create Date: 2025-07-12 14:07:40.564043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b51f08c832c'
down_revision: Union[str, None] = '4048b1f55b83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brainstorm_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interview_response_id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=200), nullable=True),
    sa.Column('generated_concepts', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['interview_response_id'], ['user_interview_responses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brainstorm_sessions_id'), 'brainstorm_sessions', ['id'], unique=False)
    op.create_table('brainstorm_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.String(length=50), nullable=False),
    sa.Column('concept_data', sa.Text(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['brainstorm_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brainstorm_favorites_id'), 'brainstorm_favorites', ['id'], unique=False)
    op.create_table('brainstorm_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('three_act_structure', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_id'], ['brainstorm_favorites.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brainstorm_stories_id'), 'brainstorm_stories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brainstorm_stories_id'), table_name='brainstorm_stories')
    op.drop_table('brainstorm_stories')
    op.drop_index(op.f('ix_brainstorm_favorites_id'), table_name='brainstorm_favorites')
    op.drop_table('brainstorm_favorites')
    op.drop_index(op.f('ix_brainstorm_sessions_id'), table_name='brainstorm_sessions')
    op.drop_table('brainstorm_sessions')
    # ### end Alembic commands ###