# /ai_rag_story_app/alembic/script.py.mako
"""Add brainstorm session models

Revision ID: 15e5388ec73d
Revises: 0bdb872a5428
Create Date: 2025-07-12 13:44:40.365302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e5388ec73d'
down_revision: Union[str, None] = '0bdb872a5428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###