# /ai_rag_story_app/alembic/script.py.mako
"""Add POINT to location scale enum

Revision ID: 28c0b2e9091c
Revises: d7d81518cde0
Create Date: 2025-07-19 11:17:20.946968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c0b2e9091c'
down_revision: Union[str, None] = 'd7d81518cde0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###