# /ai_rag_story_app/alembic/script.py.mako
"""Add published stories, comments and ratings tables

Revision ID: 2d8244251988
Revises: 661e697b0a01
Create Date: 2025-06-29 10:26:48.363061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8244251988'
down_revision: Union[str, None] = '661e697b0a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('published_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('published_url', sa.String(length=1024), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_published_stories_id'), 'published_stories', ['id'], unique=False)
    op.create_index(op.f('ix_published_stories_is_featured'), 'published_stories', ['is_featured'], unique=False)
    op.create_index(op.f('ix_published_stories_is_public'), 'published_stories', ['is_public'], unique=False)
    op.create_index(op.f('ix_published_stories_published_at'), 'published_stories', ['published_at'], unique=False)
    op.create_index(op.f('ix_published_stories_story_id'), 'published_stories', ['story_id'], unique=False)
    op.create_index(op.f('ix_published_stories_title'), 'published_stories', ['title'], unique=False)
    op.create_index(op.f('ix_published_stories_user_id'), 'published_stories', ['user_id'], unique=False)
    op.create_table('story_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['story_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_story_id'], ['published_stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_comments_id'), 'story_comments', ['id'], unique=False)
    op.create_index(op.f('ix_story_comments_is_approved'), 'story_comments', ['is_approved'], unique=False)
    op.create_index(op.f('ix_story_comments_is_deleted'), 'story_comments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_story_comments_parent_comment_id'), 'story_comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_story_comments_published_story_id'), 'story_comments', ['published_story_id'], unique=False)
    op.create_index(op.f('ix_story_comments_user_id'), 'story_comments', ['user_id'], unique=False)
    op.create_table('story_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('published_story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='valid_rating_range'),
    sa.ForeignKeyConstraint(['published_story_id'], ['published_stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('published_story_id', 'user_id', name='unique_user_story_rating')
    )
    op.create_index(op.f('ix_story_ratings_id'), 'story_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_story_ratings_published_story_id'), 'story_ratings', ['published_story_id'], unique=False)
    op.create_index(op.f('ix_story_ratings_user_id'), 'story_ratings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_ratings_user_id'), table_name='story_ratings')
    op.drop_index(op.f('ix_story_ratings_published_story_id'), table_name='story_ratings')
    op.drop_index(op.f('ix_story_ratings_id'), table_name='story_ratings')
    op.drop_table('story_ratings')
    op.drop_index(op.f('ix_story_comments_user_id'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_published_story_id'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_parent_comment_id'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_is_deleted'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_is_approved'), table_name='story_comments')
    op.drop_index(op.f('ix_story_comments_id'), table_name='story_comments')
    op.drop_table('story_comments')
    op.drop_index(op.f('ix_published_stories_user_id'), table_name='published_stories')
    op.drop_index(op.f('ix_published_stories_title'), table_name='published_stories')
    op.drop_index(op.f('ix_published_stories_story_id'), table_name='published_stories')
    op.drop_index(op.f('ix_published_stories_published_at'), table_name='published_stories')
    op.drop_index(op.f('ix_published_stories_is_public'), table_name='published_stories')
    op.drop_index(op.f('ix_published_stories_is_featured'), table_name='published_stories')
    op.drop_index(op.f('ix_published_stories_id'), table_name='published_stories')
    op.drop_table('published_stories')
    # ### end Alembic commands ###