# /ai_rag_story_app/alembic/script.py.mako
"""Add aspect_ratio column to generated_images table

Revision ID: 44b980941fe4
Revises: add_last_viewed_at
Create Date: 2025-07-27 14:25:34.551233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44b980941fe4'
down_revision: Union[str, None] = 'add_last_viewed_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'UNSUBSCRIBED', 'BOUNCED', 'COMPLAINED', name='subscriptionstatus'), nullable=False),
    sa.Column('frequency', sa.Enum('IMMEDIATE', 'DAILY', 'WEEKLY', 'MONTHLY', name='subscriptionfrequency'), nullable=False),
    sa.Column('include_categories', sa.Text(), nullable=True),
    sa.Column('include_tags', sa.Text(), nullable=True),
    sa.Column('confirmation_token', sa.String(length=255), nullable=True),
    sa.Column('unsubscribe_token', sa.String(length=255), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_emails_sent', sa.Integer(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('last_bounce_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_complaint_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unsubscribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blog_subscriptions_email_status', 'blog_subscriptions', ['email', 'status'], unique=False)
    op.create_index('idx_blog_subscriptions_frequency_status', 'blog_subscriptions', ['frequency', 'status'], unique=False)
    op.create_index('idx_blog_subscriptions_last_sent', 'blog_subscriptions', ['last_sent_at'], unique=False)
    op.create_index('idx_blog_subscriptions_user_status', 'blog_subscriptions', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_blog_subscriptions_confirmation_token'), 'blog_subscriptions', ['confirmation_token'], unique=False)
    op.create_index(op.f('ix_blog_subscriptions_email'), 'blog_subscriptions', ['email'], unique=False)
    op.create_index(op.f('ix_blog_subscriptions_id'), 'blog_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_blog_subscriptions_status'), 'blog_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_blog_subscriptions_unsubscribe_token'), 'blog_subscriptions', ['unsubscribe_token'], unique=True)
    op.create_index(op.f('ix_blog_subscriptions_user_id'), 'blog_subscriptions', ['user_id'], unique=False)
    op.drop_index(op.f('ix_referral_limits_date'), table_name='referral_limits')
    op.drop_index(op.f('ix_referral_limits_user_id'), table_name='referral_limits')
    op.drop_table('referral_limits')
    op.drop_index(op.f('ix_referral_rewards_awarded_at'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_referral_id'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_reward_type'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_user_id'), table_name='referral_rewards')
    op.drop_table('referral_rewards')
    op.drop_index(op.f('ix_referrals_anonymous_session_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_is_converted'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.add_column('generated_images', sa.Column('aspect_ratio', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('generated_images', 'aspect_ratio')
    op.create_table('referrals',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('referrals_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referred_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anonymous_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('referral_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('referral_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_converted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('has_created_story', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('has_published_story', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('first_story_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('first_publish_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name='referrals_referred_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name='referrals_referrer_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_is_converted'), 'referrals', ['is_converted'], unique=False)
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.create_index(op.f('ix_referrals_anonymous_session_id'), 'referrals', ['anonymous_session_id'], unique=False)
    op.create_table('referral_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('coin_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('referral_rewards_referral_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('referral_rewards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_rewards_pkey'))
    )
    op.create_index(op.f('ix_referral_rewards_user_id'), 'referral_rewards', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_reward_type'), 'referral_rewards', ['reward_type'], unique=False)
    op.create_index(op.f('ix_referral_rewards_referral_id'), 'referral_rewards', ['referral_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_awarded_at'), 'referral_rewards', ['awarded_at'], unique=False)
    op.create_table('referral_limits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_coins_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('visit_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('registration_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('story_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('publish_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('referral_limits_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_limits_pkey')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('referral_limits_user_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_referral_limits_user_id'), 'referral_limits', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_limits_date'), 'referral_limits', ['date'], unique=False)
    op.drop_index(op.f('ix_blog_subscriptions_user_id'), table_name='blog_subscriptions')
    op.drop_index(op.f('ix_blog_subscriptions_unsubscribe_token'), table_name='blog_subscriptions')
    op.drop_index(op.f('ix_blog_subscriptions_status'), table_name='blog_subscriptions')
    op.drop_index(op.f('ix_blog_subscriptions_id'), table_name='blog_subscriptions')
    op.drop_index(op.f('ix_blog_subscriptions_email'), table_name='blog_subscriptions')
    op.drop_index(op.f('ix_blog_subscriptions_confirmation_token'), table_name='blog_subscriptions')
    op.drop_index('idx_blog_subscriptions_user_status', table_name='blog_subscriptions')
    op.drop_index('idx_blog_subscriptions_last_sent', table_name='blog_subscriptions')
    op.drop_index('idx_blog_subscriptions_frequency_status', table_name='blog_subscriptions')
    op.drop_index('idx_blog_subscriptions_email_status', table_name='blog_subscriptions')
    op.drop_table('blog_subscriptions')
    # ### end Alembic commands ###