# /ai_rag_story_app/alembic/script.py.mako
"""Add story_type and is_shadow fields for Basic/Advanced stories

Revision ID: 50074159797a
Revises: 4ce3ce03db42
Create Date: 2025-07-08 19:49:42.477900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50074159797a'
down_revision: Union[str, None] = '4ce3ce03db42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###