# /ai_rag_story_app/alembic/script.py.mako
"""Add role-based world hierarchy associations

Revision ID: 50ca759df885
Revises: openrouter_models
Create Date: 2025-06-24 13:13:37.268594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50ca759df885'
down_revision: Union[str, None] = 'openrouter_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('world_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('world_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_world_roles_created_by_user_id'), 'world_roles', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_world_roles_id'), 'world_roles', ['id'], unique=False)
    op.create_index(op.f('ix_world_roles_is_predefined'), 'world_roles', ['is_predefined'], unique=False)
    op.create_index(op.f('ix_world_roles_world_id'), 'world_roles', ['world_id'], unique=False)
    op.create_table('story_location_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_location_associations_id'), 'story_location_associations', ['id'], unique=False)
    op.create_index(op.f('ix_story_location_associations_location_id'), 'story_location_associations', ['location_id'], unique=False)
    op.create_index(op.f('ix_story_location_associations_story_id'), 'story_location_associations', ['story_id'], unique=False)
    op.create_table('act_character_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_act_character_associations_act_id'), 'act_character_associations', ['act_id'], unique=False)
    op.create_index(op.f('ix_act_character_associations_character_id'), 'act_character_associations', ['character_id'], unique=False)
    op.create_index(op.f('ix_act_character_associations_id'), 'act_character_associations', ['id'], unique=False)
    op.create_table('act_location_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_act_location_associations_act_id'), 'act_location_associations', ['act_id'], unique=False)
    op.create_index(op.f('ix_act_location_associations_id'), 'act_location_associations', ['id'], unique=False)
    op.create_index(op.f('ix_act_location_associations_location_id'), 'act_location_associations', ['location_id'], unique=False)
    op.create_table('act_lore_item_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('lore_item_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['act_id'], ['acts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lore_item_id'], ['lore_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_act_lore_item_associations_act_id'), 'act_lore_item_associations', ['act_id'], unique=False)
    op.create_index(op.f('ix_act_lore_item_associations_id'), 'act_lore_item_associations', ['id'], unique=False)
    op.create_index(op.f('ix_act_lore_item_associations_lore_item_id'), 'act_lore_item_associations', ['lore_item_id'], unique=False)
    op.create_table('story_character_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_character_associations_character_id'), 'story_character_associations', ['character_id'], unique=False)
    op.create_index(op.f('ix_story_character_associations_id'), 'story_character_associations', ['id'], unique=False)
    op.create_index(op.f('ix_story_character_associations_story_id'), 'story_character_associations', ['story_id'], unique=False)
    op.create_table('story_lore_item_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('lore_item_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lore_item_id'], ['lore_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_lore_item_associations_id'), 'story_lore_item_associations', ['id'], unique=False)
    op.create_index(op.f('ix_story_lore_item_associations_lore_item_id'), 'story_lore_item_associations', ['lore_item_id'], unique=False)
    op.create_index(op.f('ix_story_lore_item_associations_story_id'), 'story_lore_item_associations', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_lore_item_associations_story_id'), table_name='story_lore_item_associations')
    op.drop_index(op.f('ix_story_lore_item_associations_lore_item_id'), table_name='story_lore_item_associations')
    op.drop_index(op.f('ix_story_lore_item_associations_id'), table_name='story_lore_item_associations')
    op.drop_table('story_lore_item_associations')
    op.drop_index(op.f('ix_story_character_associations_story_id'), table_name='story_character_associations')
    op.drop_index(op.f('ix_story_character_associations_id'), table_name='story_character_associations')
    op.drop_index(op.f('ix_story_character_associations_character_id'), table_name='story_character_associations')
    op.drop_table('story_character_associations')
    op.drop_index(op.f('ix_act_lore_item_associations_lore_item_id'), table_name='act_lore_item_associations')
    op.drop_index(op.f('ix_act_lore_item_associations_id'), table_name='act_lore_item_associations')
    op.drop_index(op.f('ix_act_lore_item_associations_act_id'), table_name='act_lore_item_associations')
    op.drop_table('act_lore_item_associations')
    op.drop_index(op.f('ix_act_location_associations_location_id'), table_name='act_location_associations')
    op.drop_index(op.f('ix_act_location_associations_id'), table_name='act_location_associations')
    op.drop_index(op.f('ix_act_location_associations_act_id'), table_name='act_location_associations')
    op.drop_table('act_location_associations')
    op.drop_index(op.f('ix_act_character_associations_id'), table_name='act_character_associations')
    op.drop_index(op.f('ix_act_character_associations_character_id'), table_name='act_character_associations')
    op.drop_index(op.f('ix_act_character_associations_act_id'), table_name='act_character_associations')
    op.drop_table('act_character_associations')
    op.drop_index(op.f('ix_story_location_associations_story_id'), table_name='story_location_associations')
    op.drop_index(op.f('ix_story_location_associations_location_id'), table_name='story_location_associations')
    op.drop_index(op.f('ix_story_location_associations_id'), table_name='story_location_associations')
    op.drop_table('story_location_associations')
    op.drop_index(op.f('ix_world_roles_world_id'), table_name='world_roles')
    op.drop_index(op.f('ix_world_roles_is_predefined'), table_name='world_roles')
    op.drop_index(op.f('ix_world_roles_id'), table_name='world_roles')
    op.drop_index(op.f('ix_world_roles_created_by_user_id'), table_name='world_roles')
    op.drop_table('world_roles')
    # ### end Alembic commands ###