# /ai_rag_story_app/alembic/script.py.mako
"""Add image support to Story model

Revision ID: 71aab816dd09
Revises: ce27762e9a53
Create Date: 2025-06-30 12:23:10.677067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71aab816dd09'
down_revision: Union[str, None] = 'ce27762e9a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acts', sa.Column('image_prompt_definition', sa.Text(), nullable=True))
    op.add_column('scenes', sa.Column('image_prompt_definition', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'image_prompt_definition')
    op.drop_column('acts', 'image_prompt_definition')
    # ### end Alembic commands ###