# /ai_rag_story_app/alembic/script.py.mako
"""Add story_chat_sessions and story_chat_messages tables

Revision ID: 7a34b61c6d39
Revises: 367d8bea312a
Create Date: 2025-07-09 11:48:00.974895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a34b61c6d39'
down_revision: Union[str, None] = '367d8bea312a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create story_chat_sessions table
    op.create_table('story_chat_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('story_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('focus_area', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_chat_sessions_id'), 'story_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_story_chat_sessions_story_id'), 'story_chat_sessions', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_chat_sessions_user_id'), 'story_chat_sessions', ['user_id'], unique=False)
    
    # Create story_chat_messages table
    op.create_table('story_chat_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('full_context', sa.JSON(), nullable=True),
        sa.Column('story_context', sa.JSON(), nullable=True),
        sa.Column('target_element', sa.String(length=50), nullable=True),
        sa.Column('target_element_id', sa.Integer(), nullable=True),
        sa.Column('cost_log_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['cost_log_id'], ['ai_call_logs.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['session_id'], ['story_chat_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_chat_messages_id'), 'story_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_story_chat_messages_session_id'), 'story_chat_messages', ['session_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop story_chat_messages table
    op.drop_index(op.f('ix_story_chat_messages_session_id'), table_name='story_chat_messages')
    op.drop_index(op.f('ix_story_chat_messages_id'), table_name='story_chat_messages')
    op.drop_table('story_chat_messages')
    
    # Drop story_chat_sessions table
    op.drop_index(op.f('ix_story_chat_sessions_user_id'), table_name='story_chat_sessions')
    op.drop_index(op.f('ix_story_chat_sessions_story_id'), table_name='story_chat_sessions')
    op.drop_index(op.f('ix_story_chat_sessions_id'), table_name='story_chat_sessions')
    op.drop_table('story_chat_sessions')
    
    # ### end Alembic commands ###