# /ai_rag_story_app/alembic/script.py.mako
"""Accounting Tables

Revision ID: 810af534b960
Revises: 6cfa1c57639c
Create Date: 2025-06-20 14:11:47.588489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '810af534b960'
down_revision: Union[str, None] = '6cfa1c57639c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credit_amount', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('price_usd', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('bonus_percentage', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_packages_id'), 'credit_packages', ['id'], unique=False)
    op.create_table('user_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_balance', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('total_spent', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('total_credits_added', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_balance >= 0', name='check_positive_balance'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_accounts_id'), 'user_accounts', ['id'], unique=False)
    op.create_table('user_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('balance_after', sa.DECIMAL(precision=10, scale=4), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_cost_log_id', sa.Integer(), nullable=True),
    sa.Column('credit_package_id', sa.Integer(), nullable=True),
    sa.Column('payment_reference', sa.String(length=255), nullable=True),
    sa.Column('transaction_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount != 0', name='check_non_zero_amount'),
    sa.ForeignKeyConstraint(['ai_cost_log_id'], ['ai_call_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['credit_package_id'], ['credit_packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_account_id'], ['user_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_transactions_id'), 'user_transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_transactions_id'), table_name='user_transactions')
    op.drop_table('user_transactions')
    op.drop_index(op.f('ix_user_accounts_id'), table_name='user_accounts')
    op.drop_table('user_accounts')
    op.drop_index(op.f('ix_credit_packages_id'), table_name='credit_packages')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###