# /ai_rag_story_app/alembic/script.py.mako
"""add is_free_chat_enabled to world model

Revision ID: 8caa950b083f
Revises: 810af534b960
Create Date: 2025-06-20 18:03:28.593665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caa950b083f'
down_revision: Union[str, None] = '810af534b960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first with default value
    op.add_column('worlds', sa.Column('is_free_chat_enabled', sa.Boolean(), nullable=True, default=False))
    
    # Update all existing rows to have the default value
    op.execute("UPDATE worlds SET is_free_chat_enabled = false WHERE is_free_chat_enabled IS NULL")
    
    # Now make the column NOT NULL
    op.alter_column('worlds', 'is_free_chat_enabled', nullable=False)
    
    # Create the index
    op.create_index(op.f('ix_worlds_is_free_chat_enabled'), 'worlds', ['is_free_chat_enabled'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worlds_is_free_chat_enabled'), table_name='worlds')
    op.drop_column('worlds', 'is_free_chat_enabled')
    # ### end Alembic commands ###