# /ai_rag_story_app/alembic/script.py.mako
"""Create ai_model_configurations and update ai_call_logs

Revision ID: 9b59a68ffd34
Revises: d2608829855a
Create Date: 2025-06-17 12:48:47.222259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b59a68ffd34'
down_revision: Union[str, None] = 'd2608829855a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider', sa.Enum('AZURE', 'OPENROUTER', 'OPENAI', name='ai_provider_enum'), nullable=False),
    sa.Column('model_type', sa.Enum('GENERATION', 'EMBEDDING', name='ai_model_type_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('top_p', sa.Float(), nullable=False),
    sa.Column('presence_penalty', sa.Float(), nullable=False),
    sa.Column('frequency_penalty', sa.Float(), nullable=False),
    sa.Column('is_json_mode', sa.Boolean(), nullable=False),
    sa.Column('provider_cost_input_usd_pm', sa.Float(), nullable=False),
    sa.Column('provider_cost_output_usd_pm', sa.Float(), nullable=False),
    sa.Column('user_price_input_usd_pm', sa.Float(), nullable=False),
    sa.Column('user_price_output_usd_pm', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('display_name')
    )
    op.create_index(op.f('ix_ai_model_configurations_id'), 'ai_model_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_ai_model_configurations_is_active'), 'ai_model_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_ai_model_configurations_model_name'), 'ai_model_configurations', ['model_name'], unique=False)
    op.create_index(op.f('ix_ai_model_configurations_model_type'), 'ai_model_configurations', ['model_type'], unique=False)
    op.add_column('ai_call_logs', sa.Column('model_config_id', sa.Integer(), nullable=True))
    op.add_column('ai_call_logs', sa.Column('input_prompt', sa.Text(), nullable=True))
    op.create_index(op.f('ix_ai_call_logs_model_config_id'), 'ai_call_logs', ['model_config_id'], unique=False)
    op.create_foreign_key(None, 'ai_call_logs', 'ai_model_configurations', ['model_config_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_call_logs', type_='foreignkey')
    op.drop_index(op.f('ix_ai_call_logs_model_config_id'), table_name='ai_call_logs')
    op.drop_column('ai_call_logs', 'input_prompt')
    op.drop_column('ai_call_logs', 'model_config_id')
    op.drop_index(op.f('ix_ai_model_configurations_model_type'), table_name='ai_model_configurations')
    op.drop_index(op.f('ix_ai_model_configurations_model_name'), table_name='ai_model_configurations')
    op.drop_index(op.f('ix_ai_model_configurations_is_active'), table_name='ai_model_configurations')
    op.drop_index(op.f('ix_ai_model_configurations_id'), table_name='ai_model_configurations')
    op.drop_table('ai_model_configurations')
    # ### end Alembic commands ###