# /ai_rag_story_app/alembic/script.py.mako
"""Add AI import fields to character, location, and lore_item models

Revision ID: aa0de32f671f
Revises: 993d285cfeee
Create Date: 2025-06-19 17:22:47.549858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa0de32f671f'
down_revision: Union[str, None] = '993d285cfeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('importance_rating', sa.Integer(), nullable=True))
    op.add_column('characters', sa.Column('relationships', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('geography', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('cultural_context', sa.Text(), nullable=True))
    op.add_column('locations', sa.Column('importance_rating', sa.Integer(), nullable=True))
    op.add_column('locations', sa.Column('connected_elements', sa.Text(), nullable=True))
    op.add_column('lore_items', sa.Column('importance_rating', sa.Integer(), nullable=True))
    op.add_column('lore_items', sa.Column('related_elements', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lore_items', 'related_elements')
    op.drop_column('lore_items', 'importance_rating')
    op.drop_column('locations', 'connected_elements')
    op.drop_column('locations', 'importance_rating')
    op.drop_column('locations', 'cultural_context')
    op.drop_column('locations', 'geography')
    op.drop_column('characters', 'relationships')
    op.drop_column('characters', 'importance_rating')
    # ### end Alembic commands ###