# /ai_rag_story_app/alembic/script.py.mako
"""Add scene association tables

Revision ID: add_scene_associations
Revises: 63ed8ab159f2
Create Date: 2025-06-26 11:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add_scene_associations'
down_revision: Union[str, None] = '63ed8ab159f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scene_character_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_character_associations_character_id'), 'scene_character_associations', ['character_id'], unique=False)
    op.create_index(op.f('ix_scene_character_associations_id'), 'scene_character_associations', ['id'], unique=False)
    op.create_index(op.f('ix_scene_character_associations_scene_id'), 'scene_character_associations', ['scene_id'], unique=False)
    
    op.create_table('scene_location_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_location_associations_id'), 'scene_location_associations', ['id'], unique=False)
    op.create_index(op.f('ix_scene_location_associations_location_id'), 'scene_location_associations', ['location_id'], unique=False)
    op.create_index(op.f('ix_scene_location_associations_scene_id'), 'scene_location_associations', ['scene_id'], unique=False)
    
    op.create_table('scene_lore_item_associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('lore_item_id', sa.Integer(), nullable=False),
    sa.Column('roles', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lore_item_id'], ['lore_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scene_lore_item_associations_id'), 'scene_lore_item_associations', ['id'], unique=False)
    op.create_index(op.f('ix_scene_lore_item_associations_lore_item_id'), 'scene_lore_item_associations', ['lore_item_id'], unique=False)
    op.create_index(op.f('ix_scene_lore_item_associations_scene_id'), 'scene_lore_item_associations', ['scene_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scene_lore_item_associations_scene_id'), table_name='scene_lore_item_associations')
    op.drop_index(op.f('ix_scene_lore_item_associations_lore_item_id'), table_name='scene_lore_item_associations')
    op.drop_index(op.f('ix_scene_lore_item_associations_id'), table_name='scene_lore_item_associations')
    op.drop_table('scene_lore_item_associations')
    op.drop_index(op.f('ix_scene_location_associations_scene_id'), table_name='scene_location_associations')
    op.drop_index(op.f('ix_scene_location_associations_location_id'), table_name='scene_location_associations')
    op.drop_index(op.f('ix_scene_location_associations_id'), table_name='scene_location_associations')
    op.drop_table('scene_location_associations')
    op.drop_index(op.f('ix_scene_character_associations_scene_id'), table_name='scene_character_associations')
    op.drop_index(op.f('ix_scene_character_associations_id'), table_name='scene_character_associations')
    op.drop_index(op.f('ix_scene_character_associations_character_id'), table_name='scene_character_associations')
    op.drop_table('scene_character_associations')
    # ### end Alembic commands ###