# /story_app/alembic/script.py.mako
"""add care circle provider runtime tables

Revision ID: b6c446e463aa
Revises: 7b8f4c2a1d10
Create Date: 2026-04-04 12:32:31.230136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6c446e463aa'
down_revision: Union[str, None] = '7b8f4c2a1d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_circle_provider_patient_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('schedule_expression', sa.String(length=100), nullable=True),
    sa.Column('custom_parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['care_circle_patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'provider_key', name='uq_care_circle_patient_provider')
    )
    op.create_index(op.f('ix_care_circle_provider_patient_configs_id'), 'care_circle_provider_patient_configs', ['id'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_patient_configs_patient_id'), 'care_circle_provider_patient_configs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_patient_configs_provider_key'), 'care_circle_provider_patient_configs', ['provider_key'], unique=False)
    op.create_table('care_circle_provider_run_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['care_circle_families.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['care_circle_patient_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_circle_provider_run_logs_family_id'), 'care_circle_provider_run_logs', ['family_id'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_run_logs_id'), 'care_circle_provider_run_logs', ['id'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_run_logs_patient_id'), 'care_circle_provider_run_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_run_logs_provider_key'), 'care_circle_provider_run_logs', ['provider_key'], unique=False)
    op.create_table('care_circle_provider_session_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=120), nullable=False),
    sa.Column('run_log_id', sa.Integer(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('session_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['care_circle_patient_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_log_id'], ['care_circle_provider_run_logs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_circle_provider_session_outputs_id'), 'care_circle_provider_session_outputs', ['id'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_session_outputs_patient_id'), 'care_circle_provider_session_outputs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_session_outputs_provider_key'), 'care_circle_provider_session_outputs', ['provider_key'], unique=False)
    op.create_index(op.f('ix_care_circle_provider_session_outputs_session_date'), 'care_circle_provider_session_outputs', ['session_date'], unique=False)
    op.create_table('story_chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('focus_area', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_chat_sessions_id'), 'story_chat_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_story_chat_sessions_story_id'), 'story_chat_sessions', ['story_id'], unique=False)
    op.create_index(op.f('ix_story_chat_sessions_user_id'), 'story_chat_sessions', ['user_id'], unique=False)
    op.create_table('story_chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('full_context', sa.JSON(), nullable=True),
    sa.Column('story_context', sa.JSON(), nullable=True),
    sa.Column('target_element', sa.String(length=50), nullable=True),
    sa.Column('target_element_id', sa.Integer(), nullable=True),
    sa.Column('cost_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cost_log_id'], ['ai_call_logs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['story_chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_chat_messages_id'), 'story_chat_messages', ['id'], unique=False)
    op.create_index(op.f('ix_story_chat_messages_session_id'), 'story_chat_messages', ['session_id'], unique=False)
    op.drop_constraint(op.f('care_circle_provider_catalog_provider_key_key'), 'care_circle_provider_catalog', type_='unique')
    op.drop_index(op.f('ix_care_circle_provider_catalog_provider_key'), table_name='care_circle_provider_catalog')
    op.create_index(op.f('ix_care_circle_provider_catalog_provider_key'), 'care_circle_provider_catalog', ['provider_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_care_circle_provider_catalog_provider_key'), table_name='care_circle_provider_catalog')
    op.create_index(op.f('ix_care_circle_provider_catalog_provider_key'), 'care_circle_provider_catalog', ['provider_key'], unique=False)
    op.create_unique_constraint(op.f('care_circle_provider_catalog_provider_key_key'), 'care_circle_provider_catalog', ['provider_key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_story_chat_messages_session_id'), table_name='story_chat_messages')
    op.drop_index(op.f('ix_story_chat_messages_id'), table_name='story_chat_messages')
    op.drop_table('story_chat_messages')
    op.drop_index(op.f('ix_story_chat_sessions_user_id'), table_name='story_chat_sessions')
    op.drop_index(op.f('ix_story_chat_sessions_story_id'), table_name='story_chat_sessions')
    op.drop_index(op.f('ix_story_chat_sessions_id'), table_name='story_chat_sessions')
    op.drop_table('story_chat_sessions')
    op.drop_index(op.f('ix_care_circle_provider_session_outputs_session_date'), table_name='care_circle_provider_session_outputs')
    op.drop_index(op.f('ix_care_circle_provider_session_outputs_provider_key'), table_name='care_circle_provider_session_outputs')
    op.drop_index(op.f('ix_care_circle_provider_session_outputs_patient_id'), table_name='care_circle_provider_session_outputs')
    op.drop_index(op.f('ix_care_circle_provider_session_outputs_id'), table_name='care_circle_provider_session_outputs')
    op.drop_table('care_circle_provider_session_outputs')
    op.drop_index(op.f('ix_care_circle_provider_run_logs_provider_key'), table_name='care_circle_provider_run_logs')
    op.drop_index(op.f('ix_care_circle_provider_run_logs_patient_id'), table_name='care_circle_provider_run_logs')
    op.drop_index(op.f('ix_care_circle_provider_run_logs_id'), table_name='care_circle_provider_run_logs')
    op.drop_index(op.f('ix_care_circle_provider_run_logs_family_id'), table_name='care_circle_provider_run_logs')
    op.drop_table('care_circle_provider_run_logs')
    op.drop_index(op.f('ix_care_circle_provider_patient_configs_provider_key'), table_name='care_circle_provider_patient_configs')
    op.drop_index(op.f('ix_care_circle_provider_patient_configs_patient_id'), table_name='care_circle_provider_patient_configs')
    op.drop_index(op.f('ix_care_circle_provider_patient_configs_id'), table_name='care_circle_provider_patient_configs')
    op.drop_table('care_circle_provider_patient_configs')
    # ### end Alembic commands ###
