# /ai_rag_story_app/alembic/script.py.mako
"""Add CTA content table

Revision ID: cdacb86451e6
Revises: 44b980941fe4
Create Date: 2025-08-09 13:09:24.097934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdacb86451e6'
down_revision: Union[str, None] = '44b980941fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cta_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', sa.Enum('HOME_SIDEBAR_TOP', 'HOME_MAIN_TOP', 'HOME_MAIN_BOTTOM', 'HOME_SIDEBAR_BOTTOM', 'STORY_LIST_TOP', 'WORLD_LIST_TOP', 'BLOG_SIDEBAR', name='ctaposition'), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('style', sa.Enum('GRADIENT', 'SOLID', 'BORDERED', 'MINIMAL', 'HERO', name='ctastyle'), nullable=True),
    sa.Column('background_color', sa.String(length=200), nullable=True),
    sa.Column('text_color', sa.String(length=50), nullable=True),
    sa.Column('icon_class', sa.String(length=100), nullable=True),
    sa.Column('features', sa.Text(), nullable=True),
    sa.Column('primary_button_text', sa.String(length=100), nullable=True),
    sa.Column('primary_button_url', sa.String(length=500), nullable=True),
    sa.Column('primary_button_icon', sa.String(length=50), nullable=True),
    sa.Column('secondary_button_text', sa.String(length=100), nullable=True),
    sa.Column('secondary_button_url', sa.String(length=500), nullable=True),
    sa.Column('secondary_button_icon', sa.String(length=50), nullable=True),
    sa.Column('show_for_anonymous', sa.Boolean(), nullable=True),
    sa.Column('show_for_authenticated', sa.Boolean(), nullable=True),
    sa.Column('show_for_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('campaign_name', sa.String(length=100), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cta_contents_id'), 'cta_contents', ['id'], unique=False)
    op.create_index(op.f('ix_cta_contents_is_active'), 'cta_contents', ['is_active'], unique=False)
    op.create_index(op.f('ix_cta_contents_position'), 'cta_contents', ['position'], unique=False)
    
    # Insert default CTA content
    op.execute("""
        INSERT INTO cta_contents (
            title, subtitle, position, style, background_color, text_color, icon_class,
            features, primary_button_text, primary_button_url, primary_button_icon,
            secondary_button_text, secondary_button_url, secondary_button_icon,
            show_for_anonymous, show_for_authenticated, show_for_admin, is_active,
            campaign_name, utm_source, utm_medium, utm_campaign, sort_order
        ) VALUES (
            'Start Your Story Today!',
            'Join thousands of writers using AI to bring their stories to life. Create rich worlds, compelling characters, and publish your masterpiece.',
            'HOME_SIDEBAR_TOP',
            'GRADIENT',
            'linear-gradient(135deg, var(--tblr-primary) 0%, var(--tblr-purple) 100%)',
            '#FFFFFF',
            'fas fa-rocket',
            '[{"icon": "fas fa-check-circle", "text": "AI-powered writing assistance", "color": "#10B981"}, {"icon": "fas fa-check-circle", "text": "Advanced world-building tools", "color": "#10B981"}, {"icon": "fas fa-check-circle", "text": "Publish and share your stories", "color": "#10B981"}]',
            'Start Brainstorming',
            '/ui/brainstorm',
            'fas fa-lightbulb',
            'Sign Up Free',
            '/ui/register',
            'fas fa-user-plus',
            true, true, true, true,
            'Home Sidebar CTA',
            'homepage',
            'sidebar',
            'signup',
            0
        )
    """)
    op.drop_index(op.f('ix_referral_rewards_awarded_at'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_referral_id'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_reward_type'), table_name='referral_rewards')
    op.drop_index(op.f('ix_referral_rewards_user_id'), table_name='referral_rewards')
    op.drop_table('referral_rewards')
    op.drop_index(op.f('ix_referrals_anonymous_session_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_created_at'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_is_converted'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referral_code'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referred_user_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referrer_user_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_referral_limits_date'), table_name='referral_limits')
    op.drop_index(op.f('ix_referral_limits_user_id'), table_name='referral_limits')
    op.drop_table('referral_limits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_limits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_coins_earned', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('visit_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('registration_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('story_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('publish_rewards_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('referral_limits_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_limits_pkey')),
    sa.UniqueConstraint('user_id', 'date', name=op.f('referral_limits_user_id_date_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_referral_limits_user_id'), 'referral_limits', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_limits_date'), 'referral_limits', ['date'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('referrals_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('referrer_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referred_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('anonymous_session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('referral_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source_platform', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_content_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('referral_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('is_converted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('converted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('has_created_story', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('has_published_story', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('first_story_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('first_publish_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], name='referrals_referred_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['users.id'], name='referrals_referrer_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='referrals_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_referrals_referrer_user_id'), 'referrals', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referred_user_id'), 'referrals', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referrals_referral_code'), 'referrals', ['referral_code'], unique=False)
    op.create_index(op.f('ix_referrals_is_converted'), 'referrals', ['is_converted'], unique=False)
    op.create_index(op.f('ix_referrals_created_at'), 'referrals', ['created_at'], unique=False)
    op.create_index(op.f('ix_referrals_anonymous_session_id'), 'referrals', ['anonymous_session_id'], unique=False)
    op.create_table('referral_rewards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referral_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reward_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('coin_amount', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('awarded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], name=op.f('referral_rewards_referral_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('referral_rewards_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('referral_rewards_pkey'))
    )
    op.create_index(op.f('ix_referral_rewards_user_id'), 'referral_rewards', ['user_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_reward_type'), 'referral_rewards', ['reward_type'], unique=False)
    op.create_index(op.f('ix_referral_rewards_referral_id'), 'referral_rewards', ['referral_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_awarded_at'), 'referral_rewards', ['awarded_at'], unique=False)
    op.drop_index(op.f('ix_cta_contents_position'), table_name='cta_contents')
    op.drop_index(op.f('ix_cta_contents_is_active'), table_name='cta_contents')
    op.drop_index(op.f('ix_cta_contents_id'), table_name='cta_contents')
    op.drop_table('cta_contents')
    # ### end Alembic commands ###