# /ai_rag_story_app/alembic/script.py.mako
"""Add image support to Story model

Revision ID: d2608829855a
Revises: 242cbfaa7a13
Create Date: 2025-06-16 11:52:15.223642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2608829855a'
down_revision: Union[str, None] = '242cbfaa7a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('image_prompt_definition', sa.Text(), nullable=True))
    op.add_column('stories', sa.Column('image_blob_path', sa.String(length=1024), nullable=True))
    op.add_column('stories', sa.Column('current_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stories', 'generated_images', ['current_image_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stories', type_='foreignkey')
    op.drop_column('stories', 'current_image_id')
    op.drop_column('stories', 'image_blob_path')
    op.drop_column('stories', 'image_prompt_definition')
    # ### end Alembic commands ###