# /ai_rag_story_app/alembic/script.py.mako
"""default chat

Revision ID: d4573230eacc
Revises: 96bba0a9b82e
Create Date: 2025-06-21 16:16:07.975157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4573230eacc'
down_revision: Union[str, None] = '96bba0a9b82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_model_configurations', sa.Column('is_public_chat_default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_ai_model_configurations_is_public_chat_default'), 'ai_model_configurations', ['is_public_chat_default'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_model_configurations_is_public_chat_default'), table_name='ai_model_configurations')
    op.drop_column('ai_model_configurations', 'is_public_chat_default')
    # ### end Alembic commands ###