# /ai_rag_story_app/alembic/script.py.mako
"""Add ai_summary fields to stories, acts, and scenes

Revision ID: d8fb24cfe3bc
Revises: 80ca7de98931
Create Date: 2025-06-25 09:09:30.904821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fb24cfe3bc'
down_revision: Union[str, None] = '80ca7de98931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acts', 'ai_summary')
    op.drop_column('scenes', 'ai_summary')
    op.drop_column('stories', 'ai_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('scenes', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('acts', sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###