# /ai_rag_story_app/alembic/script.py.mako
"""Add social sharing tables

Revision ID: f6f820dc421b
Revises: 46ff97ae5239
Create Date: 2025-07-04 19:53:02.255822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f820dc421b'
down_revision: Union[str, None] = '46ff97ae5239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###